server:
  port: 8082
spring:
  mustache:
    check-template-location: false
  jpa:
    database: postgresql
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  #  sql:
  #    init:
  #      mode: always
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/JsonBD}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:TestTest}
    driver-class-name: org.postgresql.Driver